services:

  caddy:
    image: caddy:2.11
    container_name: caddy
    labels:
      - 'wud.tag.include=^\d+\.\d+$$'
      - 'wud.watch.digest=true'
    environment:
      TZ: ${TZ}
    volumes:
      - ./configs/Caddyfile.custom:/etc/caddy/Caddyfile:ro
      - ${VOLUMES_PATH}/caddy/data:/data
      - ${VOLUMES_PATH}/caddy/config:/config
      - ${VOLUMES_PATH}/tailscale/run:/var/run/tailscale:ro
      - ./configs/entrypoints/caddy.sh:${CONTAINER_ENTRYPOINT_PATH:-/entrypoint.sh}:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

secrets:
  caddy_auth_password_hash:
    file: ${SECRETS_PATH}/caddy_auth_password_hash

networks:
  frontend:
    name: alpargati-pi_frontend
