services:

  caddy:
    image: caddy:2.11
    container_name: caddy
    labels:
      - 'wud.tag.include=^\d+\.\d+$$'
      - 'wud.watch.digest=true'
    environment:
      TZ: ${TZ}
    volumes:
      - ./configs/Caddyfile.custom:/etc/caddy/Caddyfile:ro
      - ${VOLUMES_PATH}/caddy/data:/data
      - ${VOLUMES_PATH}/caddy/config:/config
      - ${VOLUMES_PATH}/tailscale/run:/var/run/tailscale:ro
      - ./configs/entrypoints/caddy.sh:${CONTAINER_ENTRYPOINT_PATH:-/entrypoint.sh}:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  adguardhome:
    image: adguard/adguardhome:v0.107.71
    container_name: adguardhome
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
    environment:
      TZ: ${TZ}
    volumes:
      - ${VOLUMES_PATH}/adguardhome/work:/opt/adguardhome/work
      - ${VOLUMES_PATH}/adguardhome/conf:/opt/adguardhome/conf
    network_mode: host
    depends_on:
      - init-chown
    restart: unless-stopped
    # cap_add required for binding to privileged ports
    cap_add:
      - NET_ADMIN

  tailscale:
    image: tailscale/tailscale:v1.92.5
    container_name: tailscale
    profiles: [ "tailscale" ]
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=alpargati-pi
      - TS_USERSPACE=false
      - TS_ROUTES=192.168.0.0/24
      - TS_EXTRA_ARGS=--accept-routes
    volumes:
      - ${VOLUMES_PATH}/tailscale/data:/var/lib/tailscale
      - ${VOLUMES_PATH}/tailscale/run:/tmp
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    network_mode: host
    restart: unless-stopped

secrets:
  caddy_auth_password_hash:
    file: ${SECRETS_PATH}/caddy_auth_password_hash

networks:
  frontend:
    name: alpargati-pi_frontend
