- Documentation:
    - Homepage Docs:
        - icon: homepage.png
          href: https://gethomepage.dev/
    - Docker Hub:
        - icon: docker.png
          href: https://hub.docker.com/
- Dev:
    - Github:
        - icon: github.png
          href: https://github.com/
