- Network:
    - AdGuard Home:
        icon: mdi:shield-check
        href: http://adguard.{{DOMAIN}}
        description: Network-wide ads & trackers blocking

    - Tailscale:
        icon: mdi:vpn
        href: https://login.tailscale.com/admin/machines
        description: Secure VPN access

- Applications:
    - Vaultwarden:
        icon: mdi:safe
        href: https://vault.{{DOMAIN}}
        description: Secure Password Manager

    - SilverBullet:
        icon: mdi:notebook-edit
        href: http://notes.{{DOMAIN}}
        description: Extensible personal knowledge base

    - Memos:
        icon: mdi:note-text
        href: http://memos.{{DOMAIN}}
        description: Lightweight note-taking

- Infrastructure:
    - Syncthing:
        icon: syncthing
        href: http://sync.{{DOMAIN}}
        description: Continuous File Synchronization

    - Dozzle:
        icon: mdi:docker
        href: http://logs.{{DOMAIN}}
        description: Real-time Docker logs viewer

    - Watch Your Docker:
        icon: mdi:update
        href: http://wud.{{DOMAIN}}
        description: Container update monitoring
