title: Alpargati-Pi Dashboard
headerStyle: clean
base: http://home.{{DOMAIN}}
background:
  image: https://www.christies.com/img/LotImages/2011/NYR/2011_NYR_02470_0120_000(gregory_crewdson_untitled_from_twilight_1998062326).jpg?mode=max
  opacity: 50
  blur: 0
cardBlur: 5
theme: dark
fontFamily: Inter, sans-serif
layout:
  Infrastructure:
    style: row
    columns: 3
  Applications:
    style: row
    columns: 3
  Network:
    style: row
    columns: 3
