- logo:
    icon: https://raw.githubusercontent.com/iiiypuk/rpi-icon/refs/heads/master/128.png

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: long

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    uptime: true
    units: metric

- search:
    provider: google
    focus: true
    target: _blank
